"""Generate a synthetic test stream with ground truth known by construction.

Why this exists
---------------
Real footage cannot validate a detector. Nobody can say what the "correct"
mic RMS at t=412 of a gameplay recording is, so every assertion made against
real footage is either trivially true or unfalsifiable. This generator produces
a stream where every number is known before the pipeline touches it, and writes
those numbers to `manifest.json`. Tests read the manifest; they never hardcode.

What it produces
----------------
An MKV (§4.2/A7 — the container real ingest will see) with four audio tracks in
the §4.2 layout, plus the two capture-side files the pipeline needs:

    fixture.mkv      video + mixed/mic/game/party audio
    markers.jsonl    §4.3 shape, presses placed after their events
    anchor.json      the record-start anchor (§4.1)
    manifest.json    ground truth

Design decisions worth knowing
------------------------------
**Audio is authored numerically, not with ffmpeg's sine source.** A region's
RMS then comes out exactly where intended, and the manifest records the
*measured* RMS of the authored signal rather than a theoretical value — so the
ground truth accounts for fades, summing, and clipping headroom automatically.

**Audio is FLAC, not AAC.** Lossless, so the RMS the pipeline extracts differs
from the authored signal only by resampling. Real OBS uses AAC or PCM; for a
fixture, surviving the round trip intact matters more than realism.

**Content is band-limited below 6 kHz.** §5.3 extracts at 16 kHz, whose Nyquist
is 8 kHz. Full-band content would lose everything above 8 kHz in the downsample
and the extracted RMS would sit well below the authored value — the ground truth
would be quietly wrong, which is the worst kind of wrong for a test fixture.

**Noise segments are generated by inverse FFT and are therefore periodic**, so
tiling one to fill a track produces no seam clicks.

**The game track is loud while the mic track is quiet.** That is §4.2's
contamination case: single-track ingest cannot tell the explosion from the
operator shouting, and §4.2 calls this unrecoverable after the fact. The
fixture makes it observable.

Usage
-----
    python tests/fixtures/make_fixture.py               # 60 s, default
    python tests/fixtures/make_fixture.py --duration 600 --name long
    python tests/fixtures/make_fixture.py --force
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import sys
from dataclasses import asdict, dataclass, field
from pathlib import Path

import numpy as np
import soundfile as sf

# Importable whether run as a script or imported by conftest.
sys.path.insert(0, str(Path(__file__).resolve().parents[2]))

from clipforge import ffmpeg  # noqa: E402
from clipforge.capture import contract  # noqa: E402

OUTPUT_ROOT = Path(__file__).parent / "_generated"

#: Authoring sample rate. OBS records 48 kHz; §5.3 extracts to 16 kHz.
AUTHOR_SR = 48_000

#: Content is band-limited below this. Must stay under the 8 kHz Nyquist of the
#: 16 kHz extraction rate, with margin for the resampler's transition band.
BAND_LIMIT_HZ = 6_000

#: Raised-cosine edge on every region, to avoid clicks. A click is broadband
#: and would survive the band limit as an impulse the RMS frames would see.
EDGE_FADE_S = 0.005

#: Seconds of periodic noise generated per track, then tiled.
NOISE_SEED_S = 4.0

#: Peak ceiling for the authored tracks, in dBFS.
#:
#: Band-limited noise has a crest factor around 6.5 dB, so a region authored at
#: -6 dBFS RMS wants peaks above full scale. The container's FLAC codec is
#: integer-based, so those peaks clip on encode — measured at 1062 pinned
#: samples, dragging the loudest region 0.45 dB below its declared level while
#: still sneaking under a 0.5 dB test tolerance. A fixture that is the
#: measuring instrument for everything downstream cannot be quietly 0.45 dB out.
PEAK_CEILING_DBFS = -1.0

#: §4.2 track order. Index is the ffmpeg output stream index (0-based), which
#: is what §5.3's `-map 0:a:N` addresses.
TRACK_ORDER = ("mixed", "mic", "game", "party")

#: Track titles as OBS writes them into MKV metadata. Probe prefers these over
#: positional guessing, so the fixture has to carry realistic ones.
TRACK_TITLES = {
    "mixed": "Mixed",
    "mic": "Mic/Aux",
    "game": "Desktop Audio",
    "party": "Discord",
}


@dataclass(frozen=True)
class Region:
    """A stretch of one track held at a known level.

    An utterance is a Region too, carrying `text`/`speaker`/`voice`. That is
    deliberate rather than convenient: `measure_regions` already records the
    measured level of EVERY track across each region's window, so making
    utterances regions means the manifest carries "how loud was the mic, and how
    loud was the party track, while this line was spoken" for free — which is
    exactly the ground truth §5.8's speaker assignment has to reproduce.
    """

    track: str
    t_start: float
    t_end: float
    dbfs: float
    label: str
    #: Speech only. Empty on a noise region.
    text: str = ""
    speaker: str = ""
    voice: str = ""

    @property
    def is_speech(self) -> bool:
        return bool(self.text)


@dataclass
class FixtureSpec:
    """Everything that determines the output. Hashed for cache invalidation."""

    name: str = "short"
    duration_s: float = 60.0
    width: int = 640
    height: int = 360
    fps: str = "30"
    audio_sr: int = AUTHOR_SR
    audio_channels: int = 2
    record_start_epoch_ms: int = 1_755_123_456_789
    track_titles: bool = True
    seed: int = 20260810
    peak_ceiling_dbfs: float = PEAK_CEILING_DBFS
    generator_version: int = 2

    #: 'noise' is the original band-limited pattern; 'speech' authors dialogue
    #: (§5.7/§5.8 need something to transcribe). Selects the pattern builder.
    kind: str = "noise"

    #: Filled by build_pattern() / build_speech_pattern().
    regions: list[Region] = field(default_factory=list)
    markers: list[dict] = field(default_factory=list)
    floors_dbfs: dict[str, float] = field(default_factory=dict)

    def hash(self) -> str:
        payload = json.dumps(asdict(self), sort_keys=True, default=str)
        return hashlib.sha256(payload.encode()).hexdigest()[:12]

    @property
    def utterances(self) -> list[Region]:
        return [r for r in self.regions if r.is_speech]


# --------------------------------------------------------------------------
# the event pattern
# --------------------------------------------------------------------------

#: Quiet baseline for each track, in dBFS.
FLOORS_DBFS = {"mic": -45.0, "game": -35.0, "party": -50.0}

#: One 60-second block of events, repeated to fill the requested duration.
#: Repeating rather than stretching means a 600 s fixture has ten times the
#: events, which is what commit 9's scoring needs — a longer fixture with the
#: same three peaks would tell us nothing new.
BLOCK_S = 60.0

#: (track, offset_start, offset_end, dbfs, label)
BLOCK_REGIONS = [
    ("mic", 8.0, 12.0, -12.0, "speech_loud"),
    ("mic", 25.0, 27.0, -6.0, "speech_peak"),
    ("party", 26.0, 29.0, -14.0, "party_laugh"),
    ("mic", 40.0, 44.0, -20.0, "speech_moderate"),
    # Loud game audio over a QUIET mic. §4.2's contamination case: on a
    # single-track file this is indistinguishable from the operator shouting.
    ("game", 50.0, 53.0, -6.0, "game_explosion"),
]

#: (press_offset, kind, the event it is a reaction to). §4.3: the press lands
#: 5-15 s after the operator registers what happened, which is the entire
#: reason marker_retro_offset_s exists.
BLOCK_MARKERS = [
    (18.0, "marker_maybe", "speech_loud"),
    (35.0, "marker_definite", "speech_peak"),
    (58.0, "marker_definite", "game_explosion"),
]


def build_pattern(spec: FixtureSpec) -> None:
    """Tile the 60 s block across the requested duration."""
    regions: list[Region] = []
    markers: list[dict] = []
    blocks = max(1, math.ceil(spec.duration_s / BLOCK_S))

    for block in range(blocks):
        base = block * BLOCK_S
        for track, start, end, dbfs, label in BLOCK_REGIONS:
            if base + end > spec.duration_s:
                continue
            regions.append(
                Region(track, base + start, base + end, dbfs, f"{label}#{block}")
            )
        for offset, kind, target in BLOCK_MARKERS:
            press = base + offset
            if press > spec.duration_s:
                continue
            source = next(
                (r for r in regions if r.label == f"{target}#{block}"), None
            )
            if source is None:
                continue
            markers.append(
                {
                    "t_press": round(press, 3),
                    "kind": kind,
                    # What the operator was reacting to. §17 tunes
                    # marker_retro_offset_s against exactly this: the fraction
                    # of marker-anchored windows that contain the real moment.
                    "intended_event_t": round(source.t_start, 3),
                    "intended_event_end_t": round(source.t_end, 3),
                    "intended_label": source.label,
                    "reaction_delay_s": round(press - source.t_end, 3),
                }
            )

    spec.regions = regions
    spec.markers = markers
    spec.floors_dbfs = dict(FLOORS_DBFS)


# --------------------------------------------------------------------------
# the speech pattern (§5.6, §5.7, §5.8)
# --------------------------------------------------------------------------

#: Terms §5.7's vocabulary seeding is supposed to fix. Whisper renders these as
#: "Hawk I" and "Iron First" without seeding, and §5.7 says bad captions read as
#: amateur immediately. Recorded in the manifest so the A/B test reads its
#: targets from ground truth rather than repeating this list.
VOCABULARY_TERMS = ("Hawkeye", "Luna Snow", "Iron Fist", "Mantis", "Namor", "Jeff")

#: Drawn from §5.6's own pattern list, so phrase_detect has real material.
PASSIVE_PHRASES = ("oh my god", "no way", "did you see that", "let's go", "holy shit")

#: The phrase repeated three times at the end. §5.6 flags a phrase repeated
#: >=3x within 90 s as bit formation in real time.
REPEATED_PHRASE = "Let's go, Hawkeye."

#: (speaker, track, declared start, dBFS, text)
#:
#: Starts are declared; ENDS ARE MEASURED after rendering, because the true
#: duration of a line is whatever the synthesiser produced. The manifest records
#: what actually happened, never the intention -- the same rule as the noise
#: fixture's measured_dbfs.
SPEECH_SCRIPT = [
    # -- speaker A alone on the mic. Hero names for §5.7's vocabulary test.
    ("A", "mic", 8.0, -12.0, "Oh my god, did you see that? Hawkeye just hit that "
                             "shot from across the map."),
    ("A", "mic", 13.5, -12.0, "No way. Luna Snow ulted right as I got the pick."),
    ("A", "mic", 18.0, -13.0, "Iron Fist is diving our backline again, watch out."),

    # -- speaker B alone on the party track.
    ("B", "party", 22.5, -14.0, "I'm on Mantis, I'll try to heal you through it."),
    ("B", "party", 26.5, -14.0, "Namor's turrets are melting me, holy shit."),
    ("B", "party", 30.0, -15.0, "Okay, I'm going Jeff. This is not working."),

    # -- 32 to 52 s: NOTHING. A4 says VAD must be on or Whisper hallucinates
    #    phantom text over silence, and calls it a well-documented failure mode
    #    that would poison every downstream signal. Twenty seconds of floor
    #    turns that warning into an assertion.

    # -- both at once. §5.8's `both` branch is its only ambiguous case, and
    #    §5.4.1's overlap_speech is "everyone talking at once = something
    #    happened".
    ("A", "mic", 52.0, -11.0, "Let's go! That was actually insane, did you see it?"),
    ("B", "party", 52.6, -13.0, "Oh my god, that was insane. How did that even hit?"),

    # -- A on mic with the game loud underneath. §4.2's contamination case:
    #    on a single-track recording this is indistinguishable from shouting.
    ("A", "mic", 62.0, -14.0, "I can't believe that actually worked."),
    ("A", "mic", 67.0, -14.0, "Hawkeye, one shot, right through the Mantis."),

    # -- the repeated phrase, three times inside 90 s.
    ("A", "mic", 74.0, -12.0, REPEATED_PHRASE),
    ("A", "mic", 80.0, -12.0, REPEATED_PHRASE),
    ("A", "mic", 86.0, -12.0, REPEATED_PHRASE),
]

#: Noise regions under the speech. The loud one sits beneath A's 62-74 s lines.
SPEECH_NOISE_REGIONS = [
    ("game", 8.0, 32.0, -28.0, "game_background_early"),
    ("game", 62.0, 74.0, -6.0, "game_explosion"),
    ("game", 74.0, 92.0, -30.0, "game_background_late"),
]

#: Long enough for the script plus the trailing marker. The last line starts at
#: 86 s and the last marker presses at 92 s.
SPEECH_DURATION_S = 95.0

#: So the fixture still exercises the whole Phase 1 pipeline (§4.3 reaction lag).
SPEECH_MARKERS = [
    (24.0, "marker_maybe", 8.0, 22.0),
    (60.0, "marker_definite", 52.0, 62.0),
    (92.0, "marker_definite", 74.0, 90.0),
]


def build_speech_pattern(spec: FixtureSpec, renderer, rendered: dict) -> None:
    """Place the script, using each line's REAL rendered duration.

    `rendered` is filled with label -> conditioned audio at the authoring rate,
    so `build_track` writes exactly what was measured here.
    """
    from tests.fixtures import speech as speech_mod

    regions: list[Region] = []

    for index, (speaker, track, start, dbfs, text) in enumerate(SPEECH_SCRIPT):
        voice = speech_mod.VOICES[speaker]
        source_sr, audio = renderer.render(text, voice)
        audio = speech_mod.resample(audio, source_sr, spec.audio_sr)
        audio = speech_mod.band_limit(audio, spec.audio_sr, BAND_LIMIT_HZ)

        label = f"utt{index:02d}_{speaker}"
        end = start + audio.size / spec.audio_sr
        if end > spec.duration_s:
            raise ValueError(
                f"utterance {label} runs to {end:.2f}s, past the fixture's "
                f"{spec.duration_s}s. Lengthen the fixture or shorten the line."
            )

        rendered[label] = audio
        regions.append(Region(
            track=track, t_start=round(start, 4), t_end=round(end, 4),
            dbfs=dbfs, label=label, text=text, speaker=speaker, voice=voice,
        ))

    for track, start, end, dbfs, label in SPEECH_NOISE_REGIONS:
        if end <= spec.duration_s:
            regions.append(Region(track, start, end, dbfs, label))

    markers = [
        {
            "t_press": press,
            "kind": kind,
            "intended_event_t": event_start,
            "intended_event_end_t": event_end,
            "intended_label": "speech",
            "reaction_delay_s": round(press - event_end, 3),
        }
        for press, kind, event_start, event_end in SPEECH_MARKERS
        if press <= spec.duration_s
    ]

    spec.regions = regions
    spec.markers = markers
    spec.floors_dbfs = dict(FLOORS_DBFS)


def speech_windows(spec: FixtureSpec) -> dict:
    """Silence and overlap windows, DERIVED from where the lines actually fell.

    Declaring them would be asserting the intention. These are computed from the
    placed regions, so if a synthesiser change moves a line the manifest follows
    it and the tests still describe the file that exists.
    """
    speech = sorted(spec.utterances, key=lambda r: r.t_start)

    silence: list[list[float]] = []
    cursor = 0.0
    for region in speech:
        if region.t_start - cursor >= 2.0:
            silence.append([round(cursor, 3), round(region.t_start, 3)])
        cursor = max(cursor, region.t_end)
    if spec.duration_s - cursor >= 2.0:
        silence.append([round(cursor, 3), round(spec.duration_s, 3)])

    overlap: list[list[float]] = []
    for i, first in enumerate(speech):
        for second in speech[i + 1:]:
            if second.t_start >= first.t_end:
                break
            if second.track == first.track:
                continue
            overlap.append([
                round(second.t_start, 3), round(min(first.t_end, second.t_end), 3)
            ])

    return {
        "silence_windows": silence,
        "overlap_windows": overlap,
        "longest_silence_s": round(max((b - a for a, b in silence), default=0.0), 3),
    }


# --------------------------------------------------------------------------
# signal generation
# --------------------------------------------------------------------------


def dbfs_to_rms(dbfs: float) -> float:
    return float(10.0 ** (dbfs / 20.0))


def rms_to_dbfs(rms: float) -> float:
    return float(20.0 * math.log10(max(rms, 1e-12)))


def periodic_band_limited_noise(n: int, sr: int, cutoff_hz: float, seed: int) -> np.ndarray:
    """Noise band-limited to `cutoff_hz`, periodic over exactly `n` samples.

    Built by zeroing the high bins of an FFT, so the inverse transform wraps
    seamlessly. That periodicity is what lets a short segment tile a long track
    without a click at every seam.
    """
    rng = np.random.default_rng(seed)
    spectrum = np.fft.rfft(rng.standard_normal(n))
    freqs = np.fft.rfftfreq(n, 1.0 / sr)
    spectrum[freqs > cutoff_hz] = 0.0
    signal = np.fft.irfft(spectrum, n)
    peak = np.max(np.abs(signal))
    return signal / peak if peak > 0 else signal


def tiled(source: np.ndarray, n: int) -> np.ndarray:
    if n <= source.size:
        return source[:n].copy()
    return np.tile(source, math.ceil(n / source.size))[:n].copy()


def scale_to_rms(signal: np.ndarray, target_rms: float) -> np.ndarray:
    current = float(np.sqrt(np.mean(np.square(signal))))
    return signal * (target_rms / current) if current > 0 else signal


def apply_edge_fade(signal: np.ndarray, sr: int) -> np.ndarray:
    """Raised-cosine in/out, so region boundaries do not click."""
    fade = int(EDGE_FADE_S * sr)
    if fade <= 0 or signal.size < 2 * fade:
        return signal
    ramp = 0.5 * (1.0 - np.cos(np.linspace(0.0, math.pi, fade)))
    signal = signal.copy()
    signal[:fade] *= ramp
    signal[-fade:] *= ramp[::-1]
    return signal


def build_track(
    spec: FixtureSpec, track: str, rendered: dict | None = None
) -> np.ndarray:
    """One mono track: a quiet floor with louder regions written over it."""
    sr = spec.audio_sr
    n = int(round(spec.duration_s * sr))
    seed_len = int(NOISE_SEED_S * sr)
    track_seed = spec.seed + abs(hash(track)) % 10_000

    floor_noise = periodic_band_limited_noise(seed_len, sr, BAND_LIMIT_HZ, track_seed)
    signal = scale_to_rms(tiled(floor_noise, n), dbfs_to_rms(FLOORS_DBFS[track]))

    for index, region in enumerate(r for r in spec.regions if r.track == track):
        start = int(round(region.t_start * sr))
        end = min(int(round(region.t_end * sr)), n)
        if end <= start:
            continue

        if region.is_speech:
            # Already resampled and band-limited by build_speech_pattern, which
            # is also where its length was measured -- so it fits the window by
            # construction.
            chunk = (rendered or {})[region.label][: end - start]
            if chunk.size < end - start:
                end = start + chunk.size
        else:
            chunk = periodic_band_limited_noise(
                end - start, sr, BAND_LIMIT_HZ, track_seed + 1000 + index
            )

        chunk = scale_to_rms(chunk, dbfs_to_rms(region.dbfs))
        # Replace rather than add: the region's level is then exactly its
        # declared level, not its level plus an unstated floor.
        signal[start:end] = apply_edge_fade(chunk, sr)

    return signal


def apply_headroom(tracks: dict[str, np.ndarray], ceiling_dbfs: float) -> float:
    """Scale every source track by ONE factor so none of them clips.

    One shared factor, not one per track. Scaling each to its own peak would
    change the tracks' levels *relative to each other*, and the whole point of
    the game-loud-while-mic-quiet region is that the relationship between those
    two tracks is exact. Absolute levels shift; the manifest records what they
    became, and scoring only ever cares about relative level anyway.
    """
    peak = max((float(np.max(np.abs(signal))) for signal in tracks.values()), default=0.0)
    ceiling = dbfs_to_rms(ceiling_dbfs)
    if peak <= ceiling or peak == 0.0:
        return 1.0

    scale = ceiling / peak
    for name in tracks:
        tracks[name] = tracks[name] * scale
    return scale


def build_mixed(tracks: dict[str, np.ndarray]) -> tuple[np.ndarray, float]:
    """The §4.2 track-1 mix: everything summed, scaled off the clipping ceiling.

    This is what a single-track recording looks like, and the reason §4.2 calls
    the separation non-negotiable — once summed, the mic and the explosion
    cannot be told apart.
    """
    mixed = tracks["mic"] + tracks["game"] + tracks["party"]
    peak = float(np.max(np.abs(mixed)))
    headroom = 10 ** (-1.0 / 20.0)  # -1 dBFS ceiling
    scale = (headroom / peak) if peak > headroom else 1.0
    return mixed * scale, scale


def measure_regions(
    spec: FixtureSpec, tracks: dict[str, np.ndarray]
) -> list[dict]:
    """Measured RMS of the authored signal, per region and per track.

    Measured rather than declared, so the manifest already accounts for edge
    fades, the mix scale factor, and anything else the authoring did. Tests
    compare pipeline output against these.
    """
    sr = spec.audio_sr
    measured: list[dict] = []
    for region in spec.regions:
        start, end = int(round(region.t_start * sr)), int(round(region.t_end * sr))
        entry = {
            "label": region.label,
            "source_track": region.track,
            "t_start": region.t_start,
            "t_end": region.t_end,
            "declared_dbfs": region.dbfs,
            "measured_dbfs": {},
        }
        for name, signal in tracks.items():
            window = signal[start:end]
            if window.size:
                rms = float(np.sqrt(np.mean(np.square(window))))
                entry["measured_dbfs"][name] = round(rms_to_dbfs(rms), 3)
        measured.append(entry)
    return measured


# --------------------------------------------------------------------------
# writing
# --------------------------------------------------------------------------


def write_wavs(spec: FixtureSpec, tracks: dict[str, np.ndarray], out_dir: Path) -> list[Path]:
    """One WAV per track, in §4.2 order.

    Left and right are identical, so §5.3's `-ac 1` downmix cannot change the
    RMS and the ground truth survives it.
    """
    paths = []
    for name in TRACK_ORDER:
        mono = tracks[name]
        data = np.repeat(mono[:, None], spec.audio_channels, axis=1)
        path = out_dir / f"_src_{name}.wav"
        sf.write(path, data, spec.audio_sr, subtype="FLOAT")
        paths.append(path)
    return paths


def mux(spec: FixtureSpec, wavs: list[Path], out_path: Path, ffmpeg_bin: str) -> None:
    argv: list[str] = [
        ffmpeg_bin, "-hide_banner", "-nostdin", "-y",
        "-f", "lavfi",
        "-i", f"testsrc2=size={spec.width}x{spec.height}:rate={spec.fps}:duration={spec.duration_s}",
    ]
    for wav in wavs:
        argv += ["-i", str(wav)]

    argv += ["-map", "0:v:0"]
    for index in range(len(wavs)):
        argv += ["-map", f"{index + 1}:a:0"]

    argv += [
        "-c:v", "libx264", "-preset", "veryfast", "-crf", "30", "-pix_fmt", "yuv420p",
        # CFR at a known rate: the fixture is the reference for probe's exact
        # rational fps and for its VFR detection saying "no".
        "-fps_mode", "cfr", "-r", spec.fps,
        # FLAC keeps the authored RMS intact through the container.
        "-c:a", "flac",
        "-t", str(spec.duration_s),
    ]

    if spec.track_titles:
        for index, name in enumerate(TRACK_ORDER):
            argv += [f"-metadata:s:a:{index}", f"title={TRACK_TITLES[name]}"]

    argv.append(str(out_path))
    ffmpeg.run(argv)


def write_capture_files(spec: FixtureSpec, out_dir: Path) -> None:
    """The two Layer-A artifacts (§4.1, §4.3).

    Written through `clipforge.capture.contract`, the same module the real
    daemons use and `ingest.register` validates against. It used to restate the
    shapes here, which meant the contract existed in three places and was
    enforced in none — and a drifting anchor is undetectable downstream, because
    there is no checksum for "these timestamps are 40 seconds late".
    """
    contract.write_anchor(
        out_dir / contract.ANCHOR_FILENAME,
        spec.record_start_epoch_ms,
        contract.SOURCE_SYNTHETIC,
        written_at_epoch_ms=spec.record_start_epoch_ms,
    )

    # JsonlSink APPENDS, which is right for a daemon that may be restarted
    # mid-stream and must never truncate a session's presses -- and wrong here.
    # The generator owns this directory, and regenerating a fixture into an
    # existing one silently doubled its markers until this line existed.
    markers_path = out_dir / contract.MARKERS_FILENAME
    markers_path.unlink(missing_ok=True)

    with contract.JsonlSink(markers_path) as sink:
        for marker in spec.markers:
            sink.write(contract.marker_record(
                spec.record_start_epoch_ms + int(round(marker["t_press"] * 1000)),
                marker["kind"],
            ))


def generate(
    spec: FixtureSpec, out_root: Path = OUTPUT_ROOT, force: bool = False, renderer=None
) -> Path:
    """Build the fixture. Cached on the spec hash.

    A speech fixture renders before the cache check, because an utterance's true
    end time is whatever the synthesiser produced and the spec hash covers those
    placed regions. Synthesis of the whole script takes a few seconds; the mux
    it saves takes considerably longer.
    """
    rendered: dict = {}
    if spec.kind == "speech":
        if renderer is None:
            from tests.fixtures.speech import PiperRenderer

            renderer = PiperRenderer()
        build_speech_pattern(spec, renderer, rendered)
    else:
        build_pattern(spec)

    out_dir = out_root / spec.name
    manifest_path = out_dir / "manifest.json"
    video_path = out_dir / "fixture.mkv"

    if not force and manifest_path.is_file() and video_path.is_file():
        existing = json.loads(manifest_path.read_text(encoding="utf-8"))
        if existing.get("spec_hash") == spec.hash():
            return out_dir

    ffmpeg_bin = ffmpeg.require("ffmpeg")
    out_dir.mkdir(parents=True, exist_ok=True)

    tracks = {
        name: build_track(spec, name, rendered) for name in ("mic", "game", "party")
    }
    headroom_scale = apply_headroom(tracks, spec.peak_ceiling_dbfs)
    tracks["mixed"], mix_scale = build_mixed(tracks)

    wavs = write_wavs(spec, tracks, out_dir)
    try:
        mux(spec, wavs, video_path, ffmpeg_bin)
    finally:
        for wav in wavs:
            wav.unlink(missing_ok=True)

    write_capture_files(spec, out_dir)

    manifest = {
        "spec_hash": spec.hash(),
        "spec": {k: v for k, v in asdict(spec).items() if k not in ("regions", "markers")},
        "video": "fixture.mkv",
        "anchor": "anchor.json",
        "markers_file": "markers.jsonl",
        "duration_s": spec.duration_s,
        "fps": spec.fps,
        "resolution": f"{spec.width}x{spec.height}",
        # 0-based ffmpeg audio stream index per §4.2 / §5.3's `-map 0:a:N`.
        "expected_track_map": {name: index for index, name in enumerate(TRACK_ORDER)},
        "expected_track_titles": dict(TRACK_TITLES),
        "expected_audio_track_count": len(TRACK_ORDER),
        "expected_is_vfr": False,
        "floors_dbfs": spec.floors_dbfs,
        "mix_scale": round(mix_scale, 6),
        # One factor applied to mic/game/party together, so their levels
        # relative to each other survive exactly. Declared dB in `regions`
        # is pre-headroom; `measured_dbfs` is what is actually in the file.
        "headroom_scale": round(headroom_scale, 6),
        "peak_ceiling_dbfs": spec.peak_ceiling_dbfs,
        "regions": measure_regions(spec, tracks),
        "markers": spec.markers,
        **_speech_manifest(spec, tracks),
        "notes": {
            "band_limit_hz": BAND_LIMIT_HZ,
            "why_band_limited": (
                "16 kHz extraction (§5.3) has an 8 kHz Nyquist; unfiltered content "
                "would lose energy in the downsample and the measured RMS below "
                "would not match what the pipeline extracts."
            ),
            "audio_codec": "flac (lossless, so RMS survives the container)",
            "why_headroom": (
                "FLAC is integer-based, so float peaks above full scale clip on "
                "encode. Band-limited noise has a ~6.5 dB crest factor, so a "
                "region authored at -6 dBFS RMS would clip and read ~0.45 dB low. "
                "All source tracks share one scale factor so their relative levels "
                "are untouched."
            ),
            "contamination_case": (
                "game_explosion is loud while mic is at its floor. On the mixed "
                "track it is indistinguishable from the operator shouting, which "
                "is the failure §4.2 calls unrecoverable."
            ),
        },
    }
    manifest_path.write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    return out_dir


def _speech_manifest(spec: FixtureSpec, tracks: dict[str, np.ndarray]) -> dict:
    """The ground truth Phase 2 asserts against. Empty for a noise fixture.

    `utterances` repeats the measured levels from `regions` deliberately: the
    per-track energy across each line is what §5.8's speaker assignment must
    reproduce, and a test should not have to filter `regions` and re-derive it.
    """
    if spec.kind != "speech":
        return {}

    measured = {entry["label"]: entry for entry in measure_regions(spec, tracks)}
    utterances = [
        {
            "index": index,
            "label": region.label,
            "speaker": region.speaker,
            "track": region.track,
            "voice": region.voice,
            "text": region.text,
            "t_start": region.t_start,
            "t_end": region.t_end,
            "duration_s": round(region.t_end - region.t_start, 4),
            "declared_dbfs": region.dbfs,
            "measured_dbfs": measured[region.label]["measured_dbfs"],
        }
        for index, region in enumerate(sorted(spec.utterances, key=lambda r: r.t_start))
    ]

    return {
        "utterances": utterances,
        "vocabulary_terms": list(VOCABULARY_TERMS),
        "passive_phrases": list(PASSIVE_PHRASES),
        "repeated_phrase": REPEATED_PHRASE,
        "speaker_tracks": {"A": "mic", "B": "party"},
        **speech_windows(spec),
    }


def load_manifest(out_dir: Path) -> dict:
    return json.loads((out_dir / "manifest.json").read_text(encoding="utf-8"))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--name", default="short", help="output subdirectory name")
    parser.add_argument(
        "--duration", type=float, default=60.0,
        help="seconds (default 60; scoring needs >= 600, above the 300 s baseline)",
    )
    parser.add_argument("--width", type=int, default=640)
    parser.add_argument("--height", type=int, default=360)
    parser.add_argument("--fps", default="30", help="e.g. 30, 60, or 30000/1001")
    parser.add_argument(
        "--no-track-titles", action="store_true",
        help="omit MKV track titles, forcing probe onto positional inference",
    )
    parser.add_argument("--force", action="store_true", help="regenerate even if cached")
    parser.add_argument(
        "--kind", default="noise", choices=("noise", "speech"),
        help="'speech' authors TTS dialogue for Phase 2 (§5.6-§5.8)",
    )
    parser.add_argument(
        "--download-voices", action="store_true",
        help="fetch the Piper voice models (~60 MB each) and exit",
    )
    args = parser.parse_args(argv)

    if args.download_voices:
        from tests.fixtures.speech import download_voices

        for path in download_voices():
            print(f"  {path}")
        return 0

    # A speech fixture has to be long enough to hold the script, and 60 s is the
    # noise default. Take the longer of the two rather than silently truncating.
    duration = args.duration
    if args.kind == "speech":
        duration = max(duration, SPEECH_DURATION_S)

    spec = FixtureSpec(
        name=args.name,
        duration_s=duration,
        width=args.width,
        height=args.height,
        fps=args.fps,
        track_titles=not args.no_track_titles,
        kind=args.kind,
    )
    out_dir = generate(spec, force=args.force)
    manifest = load_manifest(out_dir)

    print(f"fixture     {out_dir}")
    print(f"spec hash   {manifest['spec_hash']}")
    print(f"duration    {manifest['duration_s']}s @ {manifest['fps']} fps, {manifest['resolution']}")
    print(f"tracks      {manifest['expected_audio_track_count']} "
          f"({', '.join(manifest['expected_track_map'])})")
    print(f"regions     {len(manifest['regions'])}")
    print(f"markers     {len(manifest['markers'])}")
    print()
    print(f"{'label':<20} {'window':<16} {'declared':>9}  measured on its own track")
    for region in manifest["regions"]:
        track = region["source_track"]
        window = f"{region['t_start']:.1f}-{region['t_end']:.1f}s"
        print(
            f"{region['label']:<20} {window:<16} {region['declared_dbfs']:>8.1f}dB"
            f"  {track}={region['measured_dbfs'][track]:.2f}dB"
            f"  mixed={region['measured_dbfs']['mixed']:.2f}dB"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
